const characters = {
		"mario": {"id": "mario", "name": "Mario"},
		"donkey_kong": {"id": "donkey_kong", "name": "Donkey Kong"},
		"link": {"id": "link", "name": "Link"},
		"link": {"id": "link", "name": "Link"},
		"samus": {"id": "samus", "name": "Samus"},
		"dark_samus": {"id": "dark_samus", "name": "Dark Samus"},
		"yoshi": {"id": "yoshi", "name": "Yoshi"},
		"kirby": {"id": "kirby", "name": "Kirby"},
		"fox": {"id": "fox", "name": "Fox"},
		"pikachu": {"id": "pikachu", "name": "Pikachu"},
		"luigi": {"id": "luigi", "name": "Luigi"},
		"ness": {"id": "ness", "name": "Ness"},
		"captain_falcon": {"id": "captain_falcon", "name": "Captain Falcon"},
		"jigglypuff": {"id": "jigglypuff", "name": "Jigglypuff"},
		"peach": {"id": "peach", "name": "Peach"},
		"daisy": {"id": "daisy", "name": "Daisy"},
		"bowser": {"id": "bowser", "name": "Bowser"},
		"ice_climber": {"id": "ice_climber", "name": "Ice Climbers"},
		"sheik": {"id": "sheik", "name": "Sheik"},
		"zelda": {"id": "zelda", "name": "Zelda"},
		"dr_mario": {"id": "dr_mario", "name": "Dr. Mario"},
		"pichu": {"id": "pichu", "name": "Pichu"},
		"falco": {"id": "falco", "name": "Falco"},
		"marth": {"id": "marth", "name": "Marth"},
		"lucina": {"id": "lucina", "name": "Lucina"},
		"young_link": {"id": "young_link", "name": "Young Link"},
		"ganondorf": {"id": "ganondorf", "name": "Ganondorf"},
		"mewtwo": {"id": "mewtwo", "name": "Mewtwo"},
		"roy": {"id": "roy", "name": "Roy"},
		"chrom": {"id": "chrom", "name": "Chrom"},
		"mr_game_and_watch": {"id": "mr_game_and_watch", "name": "Mr. Game & Watch"},
		"meta_knight": {"id": "meta_knight", "name": "Meta Knight"},
		"pit": {"id": "pit", "name": "Pit"},
		"dark_pit": {"id": "dark_pit", "name": "Dark Pit"},
		"zero_suit_samus": {"id": "zero_suit_samus", "name": "Zero Suit Samus"},
		"wario": {"id": "wario", "name": "Wario"},
		"snake": {"id": "snake", "name": "Snake"},
		"ike": {"id": "ike", "name": "Ike"},
		"pokemon_trainer": {"id": "pokemon_trainer", "name": "Pokémon Trainer"},
		"diddy_kong": {"id": "diddy_kong", "name": "Diddy Kong"},
		"lucas": {"id": "lucas", "name": "Lucas"},
		"sonic": {"id": "sonic", "name": "Sonic"},
		"king_dedede": {"id": "king_dedede", "name": "King Dedede"},
		"olimar": {"id": "olimar", "name": "Olimar"},
		"lucario": {"id": "lucario", "name": "Lucario"},
		"rob": {"id": "rob", "name": "R.O.B."},
		"toon_link": {"id": "toon_link", "name": "Toon Link"},
		"wolf": {"id": "wolf", "name": "Wolf"},
		"villager": {"id": "villager", "name": "Villager"},
		"mega_man": {"id": "mega_man", "name": "Mega Man"},
		"wii_fit_trainer": {"id": "wii_fit_trainer", "name": "Wii Fit Trainer"},
		"rosalina_and_luma": {"id": "rosalina_and_luma", "name": "Rosalina & Luma"},
		"little_mac": {"id": "little_mac", "name": "Little Mac"},
		"greninja": {"id": "greninja", "name": "Greninja"},
		"mii_fighter": {"id": "mii_fighter", "name": "Mii Fighter"},
		"palutena": {"id": "palutena", "name": "Palutena"},
		"pac_man": {"id": "pac_man", "name": "Pac-Man"},
		"robin": {"id": "robin", "name": "Robin"},
		"shulk": {"id": "shulk", "name": "Shulk"},
		"bowser_jr": {"id": "bowser_jr", "name": "Bowser Jr."},
		"duck_hunt": {"id": "duck_hunt", "name": "Duck Hunt"},
		"ryu": {"id": "ryu", "name": "Ryu"},
		"ken": {"id": "ken", "name": "Ken"},
		"cloud": {"id": "cloud", "name": "Cloud"},
		"corrin": {"id": "corrin", "name": "Corrin"},
		"bayonetta": {"id": "bayonetta", "name": "Bayonetta"},
		"inkling": {"id": "inkling", "name": "Inkling"},
		"ridley": {"id": "ridley", "name": "Ridley"},
		"simon": {"id": "simon", "name": "Simon"},
		"richter": {"id": "richter", "name": "Richter"},
		"king_k_rool": {"id": "king_k_rool", "name": "King K. Rool"},
		"isabelle": {"id": "isabelle", "name": "Isabelle"},
		"incineroar": {"id": "incineroar", "name": "Incineroar"},
		"piranha_plant": {"id": "piranha_plant", "name": "Piranha Plant"},
		"joker": {"id": "joker", "name": "Joker"},
		"hero": {"id": "hero", "name": "Hero"},
		"banjo_and_kazooie": {"id": "banjo_and_kazooie", "name": "Banjo & Kazooie"},
		"terry": {"id": "terry", "name": "Terry"},
		"byleth": {"id": "byleth", "name": "Byleth"},
		"minmin": {"id": "minmin", "name": "Min Min"},
		"steve": {"id": "steve", "name": "Steve"},
		"sephiroth": {"id": "sephiroth", "name": "Sephiroth"},
		"pyra": {"id": "pyra", "name": "Pyra"},
		"kazuya": {"id": "kazuya", "name": "Kazuya"},
		"sora": {"id": "sora", "name": "Sora"},
};
